### ISSUE TITLE
[BUG] Installed proton version don't show in Steam

### ISSUE THREAD

**Issue by PrzemekSkw** [Vysp3r/ProtonPlus#104]
**Describe the bug**
I install ProtonPlus and install GE-Proton7-55 under steam. I open steam and don't see that version.

**Expected behavior**
See proton in steam.
**Screenshots**
![image](https://user-images.githubusercontent.com/25219988/231186663-759a8c0c-81a7-4c48-bd5d-97169b7b9802.png)

![image](https://user-images.githubusercontent.com/25219988/231187163-59abf467-3893-4eff-8f78-c63df63a5e8d.png)

**Desktop (please complete the following information):**
 - OS: Archlinux
 - DE: GNOME 43
 - Type: AUR

Regards.

**Comment by Vysp3r** [comment]
Oh yeah, you need to restart Steam. I added a message for that in the textbox in the installation window.
