### ISSUE TITLE
[FEATURE] App icon following GNOME's guidelines

### ISSUE THREAD

**Issue by bragefuglseth** [Vysp3r/ProtonPlus#106]
ProtonPlus utilizes GNOME's platform libraries and design guidelines, but the current app icon looks out of place among other GNOME apps. I think the app would benefit from having an icon with [GNOME's distinct visual style](https://developer.gnome.org/hig/guidelines/app-icons.html).

I can design one if you want me to. I'll start brainstorming, but feel free to stop me if you don't consider it to be necessary :smile:

**Comment by bragefuglseth** [comment]
Some initial ideas:
- A cation (an atom with more protons than electrons). Can be represented like this:
<img src="https://user-images.githubusercontent.com/91388039/231372256-33bedda6-68c6-44ba-b687-5629523dfe32.jpeg" width="auto" height="200" />

- A battery. It isn't as strongly related to protons, but it still works as an identity marker for the app, and is a pretty good metaphor imo.
<img src="https://user-images.githubusercontent.com/91388039/231372576-c27c7127-7b6b-49ae-b0aa-491ec87f7a76.jpg" width="auto" height="200"  />

**Comment by Vysp3r** [comment]
Personally, I liked the cation thing, but I'll let you do your thing.

**Comment by BuonHobo** [comment]
I also like the proton idea. This is not a final design but it is something that came to my mind. This combines the ideas of videogames and protons, might be something to expand on

![ProtonPlusLogo](https://user-images.githubusercontent.com/60006044/231477216-cdf98c33-73e5-4491-815d-37b58b498e0e.svg)

**Comment by Vysp3r** [comment]
I mean, FlashNews is in the GNOME Circle. So maybe I won't have to change my name. I will only do it, if they make it necessary.

**Comment by Vysp3r** [comment]
The only problem with my name is the 'Non-standard punctuation or whitespace (for example: SuperWriter).', so maybe it will be alright if it's only that.

**Comment by Vysp3r** [comment]
Make sure to use https://gitlab.gnome.org/Teams/Design/HIG-app-icons/blob/master/template.svg

**Comment by Vysp3r** [comment]
I think it would be a good idea to follow that as well https://docs.elementary.io/develop/writing-apps/our-first-app/icons

**Comment by bragefuglseth** [comment]
> Make sure to use https://gitlab.gnome.org/Teams/Design/HIG-app-icons/blob/master/template.svg

I use a specialized GNOME app for templating the icon, it automatically does this for me :)

> I think it would be a good idea to follow that as well https://docs.elementary.io/develop/writing-apps/our-first-app/icons

GNOME app icons are SVG files, which means that they are infinitely scalable without creating any additional files!

**Comment by Vysp3r** [comment]
Will you make a symbolic icon too?

**Comment by bragefuglseth** [comment]
> Will you make a symbolic icon too?

Yes, that's also required for Circle membership :)

**Comment by Vysp3r** [comment]
If we ever need to switch name tho, I would probably go with Cation or something like that. I don't really get the reference of the battery.

**Comment by Vysp3r** [comment]
I think that renaming the application to battery would actually be bad since people would think its something about battery. That's why I prefer Cation.

**Comment by bragefuglseth** [comment]
> If we ever need to switch name tho, I would probably go with Cation or something like that. I don't really get the reference of the battery.

A battery builds upon protons to do useful stuff :)

But a cation icon is more obvious, of course. I can do both if needed

**Comment by Vysp3r** [comment]
St thi spoint wouldn't it be better to wait to see what the Circle says about my name?

**Comment by bragefuglseth** [comment]
Yeah, probably, but Circle reviews take some time. I’ll do the cation for now

**Comment by bragefuglseth** [comment]
This is the current state of the icon. I'm waiting for some feedback in the GNOME App Icon Design group, but I'll open a PR when the icon is ready and looks good to some of the other designers.

![Preview](https://user-images.githubusercontent.com/91388039/232158644-ad9483ee-6874-4f50-9c04-7d66ae5778e6.png)

**Comment by Vysp3r** [comment]
Thanks again for that, I really appreciate you taking your time for that.

**Comment by Vysp3r** [comment]
Hey, I will close this since I don't want to join the GNOME Circle anymore. I like my current icon and I don't want to change it if I'm not a part of the GNOME Circle.
