### ISSUE TITLE
[FEATURE] New app name

### ISSUE THREAD

**Issue by bragefuglseth** [Vysp3r/ProtonPlus#108]
The name ProtonPlus fits the purpose of the app, but it unfortunately doesn't follow GNOME's [naming guidelines](https://developer.gnome.org/hig/guidelines/app-naming.html):

> A good name should avoid using trademarks or names of other projects (for example: GNOME Instant Video).

The current app name includes "Proton", and even though it *does* build upon the Proton compatibility layer, it's not directly affiliated with it.

> A good name should avoid non-standard punctuation or whitespace (for example: SuperWriter).

"ProtonPlus" is not standard punctuation, and GNOME apps don't follow this convention.

## Possible solutions

Awaiting an initial response from the GNOME Circle committee is of course possible, but they're currently a little behind on reviews, so it might take some time. I'm pretty confident that this is one of the things they'll mention first, which is why I'm opening this issue now.

If the app is aiming for inclusion in GNOME Circle, it should have a name that adheres to GNOME's guidelines and integrates well with other GNOME app names. I suggest "Cation". It follows the gudelines, it's what the new proposed app icon (#107) resembles, it's unique, and it fits the purpose of the app.

There are maaaaaany other possible names too, of course. The intention with this issue isn't to force a renaming instantly, but to start a discussion about it :smile:

**Comment by Vysp3r** [comment]
I've asked the people in the Matrix of GNOME Circle to give me idea for a rebrand.

**Comment by Vysp3r** [comment]
Someone said the name Nucleus and I like it. What do you think?

**Comment by bragefuglseth** [comment]
That’s a pretty good name IMO!

**Comment by Vysp3r** [comment]
I'll merge the name change requests in v0.5

**Comment by bragefuglseth** [comment]
I can design a new icon that fits new name if it’s needed.

**Comment by bragefuglseth** [comment]
Thank you very much for the kind words, but I don't think I'm going to defend this :)

If @Vysp3r feels like the current app identity works and resonates with the target audience, there's little reason to go through the effort of changing it.

**Comment by Vysp3r** [comment]
I'm not 100% closed to the idea, but I would first like to finish the update I'm working on which follows the GNOME HIG a bit more.

**Comment by bragefuglseth** [comment]
It’s possible to change the app ID in a partially non-breaking way AFAIK. I can ask some Flathub guys about it. GitHub can automatically redirect people to the new repository name if it’s changed.

**Comment by Vysp3r** [comment]
Well if you say GitHub can redirect to a new page and it may be possible to change the app id it would certainly open me more to the idea.

**Comment by Vysp3r** [comment]
![image](https://github.com/Vysp3r/ProtonPlus/assets/62019735/70c04c66-b331-4c7f-a9f5-b5871f29f381)

**Comment by bragefuglseth** [comment]
Ok, I've done a little research, and:
- To change the app ID, you'll need to make a new submission, [mark the current one as End Of Life (EOL)](https://github.com/flathub/flathub/wiki/App-Maintenance#end-of-life), and add the new ID in a metadata field. Local Flatpak clients can use this information to rename the config directory and keep the user data.
- [Changing the repo name](https://docs.github.com/en/repositories/creating-and-managing-repositories/renaming-a-repository) is pretty easy, GitHub automatically handles the rest for you.

**Comment by Vysp3r** [comment]
I've asked around and it seems like there's not enough vote on changing the name. I will wait a bit, but the polls are not in favour enough for me to accept that change. What we could do is make the current logo fit the icon template so it's the same size as the other application. That would help a bit to fit in.

**Comment by bragefuglseth** [comment]
An earlier version of the icon I made had a plus sign as one of the protons. I could put it back again. It would make the icon fit the current name *and* fit stylistically in with other app icons.

**Comment by Vysp3r** [comment]
Well what I can do is ask people if they would be alright with just changing the icon to the current design you have, which I agree with @gargullia is pretty nice. I could ask for that other icon too at the same time to see what people prefer.
