### ISSUE TITLE
[FEATURE] DXVK, VKD3D & NVAPI Updater

### ISSUE THREAD

**Issue by massatt212** [Vysp3r/ProtonPlus#113]
DXVK Updater for steam proton and Custom proton builds, some people want to use older versions of protons with new DXVK, VKD3D and NVAPI, idk if its possible but it would be very nice to be able to 1 click update instead of going back and forward to folders.

**Comment by Vysp3r** [comment]
Is it possible on Steam to have a specific DXVK/VKD3D/NVAPI version? I know you can enable them with launch parameters, but I've never seen something for using a specific version. Do you have a link to a documentation page or a post somewhere so that I am not completely lost?

**Comment by massatt212** [comment]
https://github.com/HansKristian-Work/vkd3d-proton/actions
https://github.com/HansKristian-Work/vkd3d-proton/actions/runs/5071402814

https://github.com/doitsujin/dxvk/actions
https://github.com/doitsujin/dxvk/actions/runs/5069381279

if is this you need or something else?

**Comment by Vysp3r** [comment]
Aren't the binaries for DXVK and such bundled in the proton files on Steam?

**Comment by massatt212** [comment]
prob cant be done, but the location of dxvk and vkd3d is \GE-Proton8-3\files\lib64\wine

**Comment by Vysp3r** [comment]
Yeah, I just checked and they're bundled with the proton files. I can try to manually change the files inside with another version I get online and if that works I can probably do something about your request. If you want to make sure your request is added, you could make me a little step by step guide on how to replace the binaries to make my life easier.

**Comment by massatt212** [comment]
im not good at all my programing, but the dll can be pasted over overwritten.

**Comment by Vysp3r** [comment]
Currently I'm redoing a lot of the UI with a lot of optimizations. It will take some time, but if until then you can make me a step by step guide on how to replace the binaries properly so that it just works when I try to follow your guide it will be faster for me.

Regarding you not being a programmer, I didn't ask you to code anything. I just want to download the DXVK files from github and manually replace them in your  \GE-Proton8-3\files\lib64\wine folder and mess around with that until it works and tell me what you did to make it work.

**Comment by massatt212** [comment]
i can make a video on how i do it, is that better?

**Comment by Vysp3r** [comment]
Sure I do not mind

**Comment by Vysp3r** [comment]
No worries ahah

**Comment by Vysp3r** [comment]
There`s already a plugin for the Steam Deck for that I think. I mainly want to focus on GNOME stuff.

**Comment by massatt212** [comment]
I don't think so, or I haven't found it.

**Comment by Vysp3r** [comment]
I will close this since I decided not to add such feature. I think it's too advanced and for the number of people that will use that it's not really worth it. Thank you for your feedback tho.

**Comment by massatt212** [comment]
Ok
