### ISSUE TITLE
Error when installing a runner for Steam for the first time

### ISSUE THREAD

**Issue by FelisDiligens** [Vysp3r/ProtonPlus#119]
**Describe the bug**
ProtonPlus fails with an error message when installing a runner (e.g. GE-Proton8-4) for Steam for the first time, because of a missing folder.

**To Reproduce**
1. Select Steam
2. Expand Proton-GE
3. Click on the download icon button of any version

**Expected behavior**
It should download and go to 100%, then display a trash icon button.

**Screenshots**
![image](https://github.com/Vysp3r/ProtonPlus/assets/47528453/029a6481-d422-4640-acb4-f08435b65bf3)

**Desktop (please complete the following information):**
 - OS: Fedora 38
 - DE: GNOME 44.1 (x11)
 - Type: Flatpak (ProtonPlus v0.4.3)

**Additional context**
Terminal output:
```
$ flatpak run com.vysp3r.ProtonPlus
** Message: 17:54:48.054: web.vala:54: Fehler beim Öffnen der Datei »/home/[redacted]/.local/share/Steam/compatibilitytools.d/GE-Proton8-4.tar.gz«: Datei oder Verzeichnis nicht gefunden
```

Manually creating the missing folder (`$HOME/.local/share/Steam/compatibilitytools.d`) fixes this issue and the runner shows up in Steam as usual.  
So, it's not a big deal, just wanted to let you know. :)

**Comment by Vysp3r** [comment]
Thank you for reporting that. Normally, I made it so it creates the missing directories, but I may have broken it in  the last update. I will look into it tonight!

**Comment by Vysp3r** [comment]
There you go, I added a check when the application start to make sure those folder exists. It seems to be working fine. I will push an update when I can. If it still does not work for you after the update, make sure to re-open this issue. Here's the commit for reference: https://github.com/Vysp3r/ProtonPlus/commit/5b76d03cbdc087c272f876f21211ad97b972a3cd.

**Comment by FelisDiligens** [comment]
Just tested it again and it works like a charm! Thanks for your quick response. :)

**Comment by roof98** [comment]
Just installed and I am getting this error was well, identical to OP

**Comment by Vysp3r** [comment]
@roof98 Can you send the error log along with the name of the launcher and if it's the local, flatpak or snap version.

**Comment by Vysp3r** [comment]
@roof98 Are you alive? 😶‍🌫️
