### ISSUE TITLE
[FEATURE] Add ability to download older proton-ge versions

### ISSUE THREAD

**Issue by jntdofe** [Vysp3r/ProtonPlus#129]
**Is your feature request related to a problem? Please describe.**
Sometimes it can be annoying when a game only works with an older proton-ge version that is not supported by ProtonPlus and the only option is to go to GE's github to download it. Ex: Ys 1 (1 and 2 complete) only displays the initial cinematic with proton-ge 6.21-2  and the earliest version available by the app is 7-38.

**Describe the solution you'd like**
I would like to have an option to display older versions of proton-ge

**Describe alternatives you've considered**
A solution to not clutter the interface with lots of versions could be at the end of the list put a "more" or "older" button that leads to a popup window with older versions of proton-ge available to download.

**Comment by Vysp3r** [comment]
That was on my list already, but I'll keep the issue open as a tracker. I wasn't planning to work on ProtonPlus this weekend, but I guess I can push myself to do it. I haven't really worked on it for some time now.

**Comment by Vysp3r** [comment]
I just got a two week break, I will start working on adding your request tomorrow morning.

**Comment by Vysp3r** [comment]
I've implemented the feature. I just need to test it a bit to make sure everything still works.

**Comment by Vysp3r** [comment]
I added a simple load more releases row when there's more to see.
![image](https://github.com/Vysp3r/ProtonPlus/assets/62019735/a5d82890-80b1-46f2-9e58-c45307e6cc89)

**Comment by Vysp3r** [comment]
It's now mostly working, I just have a few problems to fix. It shouldn't be too long.

**Comment by Vysp3r** [comment]
Fixed everything on my list. I now just need to re-test everything to make sure I did not forget anything.

**Comment by jntdofe** [comment]
Thank you so much for working on it, it will surely help me and a lot more people playing older games.

**Comment by Vysp3r** [comment]
@jntdofe It's now finished. I've tested it a bit and everything looks fine to me. If you have any problem just create an issue and I'll do my best to fix it. Here's the pull request if you're interested https://github.com/Vysp3r/ProtonPlus/pull/132.

**Comment by Vysp3r** [comment]
I just have a few more things I want to do before making an update, but I'm pretty sure I should be able to finish what I want before the end of the week.
