### ISSUE TITLE
[BUG] Clicking to delete steam proton versions in ProtonPlus isn't deleting files

### ISSUE THREAD

**Issue by foundObjects** [Vysp3r/ProtonPlus#130]
**Describe the bug**
Clicking the trash can to delete older versions of Proton-GE shows the "Deleted X" message in the app but doesn't delete the CompatibilityTools.d/ files on disk.

**To Reproduce**
Open ProtonPlus
Select Steam
Select Proton-GE
Delete any version

**Expected behavior**
Files should be removed as expected

**Screenshots**
n/a

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - DE: GNOME 44(? current version)
 - Type: Flatpak

**Additional context**
I'm not sure when this started happening, it was working fine the last time I cleaned up older versions of Proton-GE several weeks ago.

**Comment by Vysp3r** [comment]
It deletes it after the popup disappear normally. Are you sure you just did not wait for that popup to disappear?

**Comment by foundObjects** [comment]
> It deletes it after the popup disappear normally. Are you sure you just did not wait for that popup to disappear?

Ah, that's exactly what's happening, thanks!

Nitpick incoming:

I feel like that dialog would be less confusing if it had an explicit "OK" or "Proceed" button so it was more clear that deletion will happen after the dialog closes? As of now the X is basically acting like an OK button if you don't want to wait for the dialog to timeout.

Anyway, thanks, now I understand what's going on.

**Comment by Vysp3r** [comment]
Yeah you're right, I guess I could use the dialog as a way to confirm you really want to delete the tool and the x would cancel it instead. Thank you for your input!

**Comment by Vysp3r** [comment]
@foundObjects There you go I merged the new dialog https://github.com/Vysp3r/ProtonPlus/pull/131!

**Comment by foundObjects** [comment]
> @foundObjects There you go I merged the new dialog https://github.com/Vysp3r/ProtonPlus/pull/131!

Thanks! Sorry for the nitpick, I just figured if I'm confused by the behaviour someone else probably will be too.

Cheers!
