### ISSUE TITLE
[FEATURE] A Download Indicator

### ISSUE THREAD

**Issue by Heus-Sueh** [Vysp3r/ProtonPlus#148]
**Is your feature request related to a problem? Please describe.**
A Download indicator that shows the multiple things being downloaded by the user

**Describe the solution you'd like**
A Download indicator
![image](https://github.com/Vysp3r/ProtonPlus/assets/98482469/5120fd5a-76cf-4747-af13-7a4f32a0a743)
[Screencast from 2023-09-01 18-17-11.webm](https://github.com/Vysp3r/ProtonPlus/assets/98482469/65777da5-3602-4fdd-9477-1ec86f829027)

**Describe alternatives you've considered**
None.

**Additional context**
when you want to download the latest version of some wine, you want to do it for Steam, Bottles, Lutris...etc and as you change pages it is not possible to see if the package has been downloaded, is downloading or if it has already been completed for that reason a download indicator could be interesting.

**Comment by Vysp3r** [comment]
I guess I could add something top right for recent activity for now until I add my notification system.

**Comment by Vysp3r** [comment]
I will add that for the next update since it's not that hard to do.

**Comment by Vysp3r** [comment]
I am changing the flow of the application a bit and this will not be required anymore so I will close this issue.
