### ISSUE TITLE
[BUG] Unacceptable TLS certificate error

### ISSUE THREAD

**Issue by moutazhaq** [Vysp3r/ProtonPlus#168]
**Describe the bug**
Expanding the dropdown list for any runner results in an indefinite wait. Spinner keeps spinning forever.

**To Reproduce**
1. Start ProtonPlus flatpak from the command line.
2. In the left panel, select Steam or Lutris.
3. In the right panel, click on any runner.
4. Spinner appears to indicate that list of runner versions is loading but keeps spinning forever.
5. Observe error in console: `** Message: 20:10:39.124: web.vala:18: Unacceptable TLS certificate`

**Expected behavior**
List of available runner versions should appear when a runner is expanded.

**Desktop**
 - OS: PopOS 22.04
 - DE: GNOME 42.5
 - Type: Flatpak version 0.4.9

**Comment by Vysp3r** [comment]
I'll check when I come back from work.

**Comment by Vysp3r** [comment]
I am unable to replicate on my side. Are you using a VPN or do you have a special network configuration?

**Comment by moutazhaq** [comment]
After some futher investigation, it looks like this is an issue with my system not ProtonPlus, so I'll close this issue.
