### ISSUE TITLE
[FEATURE] New app Icon

### ISSUE THREAD

**Issue by Enderteck** [Vysp3r/ProtonPlus#169]
I made an icon. Can be improved. If wanted I could change the font to the previous one and/or add back the P.

It's a mix of the new Proton logo and a plus.

Adding a color might be cool too. Need feedback.

Old one vs the one I made:

![com vysp3r ProtonPlus](https://github.com/Vysp3r/ProtonPlus/assets/123917079/ab915ee9-6cbe-4884-b1a6-e88033a22155)

![Proton Plus 256x256](https://github.com/Vysp3r/ProtonPlus/assets/123917079/46978e45-554f-4025-a422-2324d17673ad)

Valve proton's logo:

https://steamdeckhq.com/news/valves-proton-compatibility-layer-has-a-logo/

Wasn't able to find a .svg file of it hence the recreation at a 45° rotation.

**Comment by Vysp3r** [comment]
That's actually ain't that bad.
It's the first icon someone made, that's actually tempting me to make the change.
Nice work.

Does this logo respect https://developer.gnome.org/hig/?
I am not that familiar with it so I couldn't really tell.

Regarding adding a color I couldn't tell you either.
It looks good to me now, but I can ask around if you want.

**Comment by Enderteck** [comment]
I'll change it a bit if it need to align with the the Gnome human interface guidelines. I probably won't add any color but I'll see with these rules in mind.

**Comment by Enderteck** [comment]
I'm adapting it to the gnome guidelines rn and I'll make a symbolic icon too

**Comment by Vysp3r** [comment]
Hey, just wanted to know if you were still interested in doing the icon?

**Comment by Enderteck** [comment]
Yeah sorry had a lot of stuff to do I'm going back to it

**Comment by Vysp3r** [comment]
@Enderteck No worries, I get it and thank you for you help.

**Comment by Enderteck** [comment]
Ok, made a new icon which should look way more like other Gnome apps.

![ProtonPlus](https://github.com/Vysp3r/ProtonPlus/assets/123917079/5f455b0a-89bc-4f5f-b8af-99c44a52560b)

I used gnome's palette and tried to make it with shading similar to other icons.

Feel free to use it or suggest anything to improve it.

I don't do a lot of Gnome app icons so it may not look great yet.

**Comment by Vysp3r** [comment]
I will send you a few icons I like for inspiration tomorrow.
Really busy today.

**Comment by Enderteck** [comment]
OK

**Comment by Vysp3r** [comment]
Since there's no update on this and I get it it's fine, I will close this issue.
Thank you again for the time you've spent on this and trying to improve the logo I still appreciate the effort.
