### ISSUE TITLE
[FEATURE] Add RTSP variant of GE Proton to the supported types

### ISSUE THREAD

**Issue by ToasterUwU** [Vysp3r/ProtonPlus#173]
It would be awesome if i can also download https://github.com/SpookySkeletons/proton-ge-rtsp from this tool. 

Its a Proton Version based on GE, modified to make RTSP Streams in Games work.
This is technically not specific to one Game, but it is most commonly used for VRChat, since there are lots of Video Players in VRChat that use RTSP and are just broken without this specific proton version, either black screen and no sound or worst case the world/game crashes.

**Comment by Vysp3r** [comment]
I will look into that this weekend while also updating ProtonPlus for GNOME 46.
