### ISSUE TITLE
[BUG] Cannot download Proton-TKG

### ISSUE THREAD

**Issue by Serph91P** [Vysp3r/ProtonPlus#196]
**Describe the bug**
It does not matter what version of proton-tkg you try, you cannot download any in the tool. From the GitHub it works, maybe the link it tries to download from is wrong?

**To Reproduce**

1. Open ProtonPlus
2. Select Steam
3. Select Proton-TKG
4. try to download a version of it
5. does now download

**Expected behavior**
The proton-tkg build gets downloaded.

**Desktop (please complete the following information):**
Operating System: EndeavourOS 
Installed from AUR

**Additional context**
this is the log I can get:

protonplus

(protonplus:8750): Gtk-WARNING **: 08:42:51.422: Unknown key gtk-modules in /home/maxe/.config/gtk-4.0/settings.ini

(protonplus:8750): Adwaita-WARNING **: 08:42:51.475: Using GtkSettings:gtk-application-prefer-dark-theme with libadwaita is unsupported. Please use AdwStyleManager:color-scheme instead.

** Message: 08:43:01.902: web.vala:90: Verbindung mit nightly.link ist gescheitert: Verbindungsaufbau abgelehnt

The last message translates to "Connection to nightly.link failed. Connection refused."

**Comment by Vysp3r** [comment]
Are you able to download from that link?
https://nightly.link/Frogging-Family/wine-tkg-git/actions/runs/10141064506/proton-tkg-build.zip

**Comment by Vysp3r** [comment]
I just tried and it worked for me and with the error you're getting I am pretty sure it's a network error on your side.
I can help you if you want, but I'll need more information.

**Comment by Serph91P** [comment]
> Are you able to download from that link? https://nightly.link/Frogging-Family/wine-tkg-git/actions/runs/10141064506/proton-tkg-build.zip

Just tested this and it seems the .link domain gets blocked for whatever reason from my routers firewall. Thanks for the support.
