### ISSUE TITLE
[FEATURE] Close app on Ctrl+Q

### ISSUE THREAD

**Issue by largestgithubuseronearth** [Vysp3r/ProtonPlus#218]
**Is your feature request related to a problem? Please describe.**
Many apps use the convention of having Ctrl+Q be an accelerator for closing the app but ProtonPlus doesn't and it messes with my muscle memory.

**Describe the solution you'd like**
Please make pressing Ctrl+Q close the app just like most other GTK apps.

**Comment by Vysp3r** [comment]
I will add in the next update which will be coming soon.
I just need to finish my work on the SteamTinkerLaunch feature request first.

**Comment by Vysp3r** [comment]
I should be able to push the update tomorrow night if everything goes well
