### ISSUE TITLE
[BUG] I can't make it run on Windeau

### ISSUE THREAD

**Issue by xavierhd** [Vysp3r/ProtonPlus#24]
**Describe the bug**
It does not work. Where is the exe file to install.

**Desktop (please complete the following information):**
 - OS: Windeau
 - DE: Vista Home Edition
 - Type: GitHub

**Additional context**
😂

**Comment by windblows95** [comment]
Try deleting the C:\Windows\System32 directory, as it is known to cause many issues with multiple software

**Comment by xavierhd** [comment]
It work! Thanks!
