### ISSUE TITLE
[BUG] unexpected error when try to install a runner (PROTON-GE)

### ISSUE THREAD

**Issue by ChrisLauinger77** [Vysp3r/ProtonPlus#240]
**Describe the bug**
`flatpak` run com.vysp3r.ProtonPlus
cat: /etc/lsb-release: file or directory not found`
(on debian its /etc/os-release)
ProtonPlus still opens but it does not show already installed PROTON-GE versions and also I cannot install a new one

* Message: 17:42:19.664: web.vala:104: Error opening file »/home/christian/.local/share/Steam/compatibilitytools.d/GE-Proton9-13.tar.gz«: File or directory not found

**To Reproduce**
1. start the flatpak version
2. Click on 'install' under PROTON-GE
3. See error "unexpected error occured"

**Expected behavior**
PROTON-GE gets downloaded and installed. 

**Desktop (please complete the following information):**
 - OS: debian trixie (testing)
 - DE: GNOME 46
 - Type: Flatpak
 - https://gist.github.com/ChrisLauinger77/ac3f8a7cf89c1499688617bbad1d0cdb

**Comment by Vysp3r** [comment]
Weird I tested everything multiple time before releasing

**Comment by Vysp3r** [comment]
Could you check the permission of the application with Flatseal and give me a screenshot with all the values.
I want to make sure this is not because the permissions did not set properly before starting my investigation.

**Comment by Arcitec** [comment]
@ChrisLauinger77 Yeah please show a screenshot of your current Filesystem permissions in Flatseal.

And then try pressing the Reset button at the top of Flatseal to reset to the default ProtonPlus permissions.

PS: Ignore the os-release line. It's normal because we check both files.

**Comment by Arcitec** [comment]
Oh and when do you see this error?

> Message: 17:42:19.664: web.vala:104: Error opening file »/home/christian/.local/share/Steam/compatibilitytools.d/GE-Proton9-13.tar.gz«: File or directory not found

Do you see that AFTER you click on the download button for GE-Proton?

**Comment by Arcitec** [comment]
These are the correct default permissions which I have verified are being correctly set from Flathub:

![image](https://github.com/user-attachments/assets/d8fed06e-ed58-4a4b-9102-24d5839cbac3)

And I just went and installed the latest `GE-Proton9-13` with it, into my own native Steam exactly like your path:

![image](https://github.com/user-attachments/assets/1c4cba66-fc94-4a0b-9a82-29570dd9fa61)

It went flawlessly.

So I see 3 possible reasons:

- Could there have been a network error while you were downloading GE-Proton? What happens if you retry?
- Disk permission error: Do you have write access to `/home/christian/.local/share/Steam/compatibilitytools.d`?
- Flatpak permissions error: Did you override something in the past, and now it's broken? Please check Flatseal and let us know what it was before resetting permissions. :)

**Comment by ChrisLauinger77** [comment]
> Oh and when do you see this error?
> 
> > Message: 17:42:19.664: web.vala:104: Error opening file »/home/christian/.local/share/Steam/compatibilitytools.d/GE-Proton9-13.tar.gz«: File or directory not found
> 
> Did that appear immediately AFTER you clicked on the download button for GE-Proton?

Not immediatly but after 3-4 seconds yes

**Comment by ChrisLauinger77** [comment]
> @ChrisLauinger77 Could you check the permission of the application with Flatseal and give me a screenshot with all the values. I want to make sure this is not because the permissions did not set properly before starting my investigation.

![grafik](https://github.com/user-attachments/assets/04216631-9a88-4e06-b4a7-fbd357fafa7a)
![grafik](https://github.com/user-attachments/assets/0ef14123-4b9a-4bf1-940b-8b1a8d37456c)
![grafik](https://github.com/user-attachments/assets/7227c452-5193-447f-9313-6d812016046f)
![grafik](https://github.com/user-attachments/assets/8c611331-37a1-470f-a14c-e19ff3eea823)

**Comment by ChrisLauinger77** [comment]
> These are the correct default permissions which I have verified are being correctly set from Flathub:
> 
> ![image](https://private-user-images.githubusercontent.com/38923130/367547611-d8fed06e-ed58-4a4b-9102-24d5839cbac3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYzODI2ODYsIm5iZiI6MTcyNjM4MjM4NiwicGF0aCI6Ii8zODkyMzEzMC8zNjc1NDc2MTEtZDhmZWQwNmUtZWQ1OC00YTRiLTkxMDItMjRkNTgzOWNiYWMzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE1VDA2Mzk0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNhNDRhZGRkZjZhMDJhNmRmOGEzNjAzNDczNDMzNzAyNmEwOTEzN2RiMTY5NWExNmI2YTYzNTJkYWIxM2JkZjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.W9OKYNNlI8BvbdQqEre2Gmrg9gIo_Dtrz2C9CbuywOI)
> 
> And I just went and installed the latest `GE-Proton9-13` with it, into my own native Steam exactly like your path:
> 
> ![image](https://private-user-images.githubusercontent.com/38923130/367547657-1c4cba66-fc94-4a0b-9a82-29570dd9fa61.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYzODI2ODYsIm5iZiI6MTcyNjM4MjM4NiwicGF0aCI6Ii8zODkyMzEzMC8zNjc1NDc2NTctMWM0Y2JhNjYtZmM5NC00YTBiLTlhODItMjk1NzBkZDlmYTYxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE1VDA2Mzk0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJjNGMzNTQ4ZTk0NjgwNjRkYzVhNzJmNjkyOGJjMTM0M2U1YjdjM2Q4ZWE4Y2Y0NTIyMDg1N2EwYTIwZTkzYmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zXhtL7iRKiLITfBooexB1U_Yezbn4seBzwPTEToUMx0)
> 
> It went flawlessly.
> 
> So I see 3 possible reasons:
> 
>     * Could there have been a network error while you were downloading GE-Proton? What happens if you retry? But this is unlikely to be the reason, because ProtonPlus will warn if it fails to download a file, so it's probably not this.
> 
>     * Disk permission error: Do you have write access to `/home/christian/.local/share/Steam/compatibilitytools.d`?
> 
drwxr-xr-x  3 christian users         4096 14. Sep 17:29 compatibilitytools.d
yes, sure
>     * Flatpak permissions error: Did you override something in the past, and now it's broken? Please check Flatseal and let us know what it was before resetting permissions. :)
Reset permissions in flatseal did not work

I did not change anything in permissions - ProtonPlus was updated over gnome software.
Steam is not installed via flatpak - I used the debian package.
Before the update to 0.4.16 it worked.

**Comment by Vysp3r** [comment]
Could you try giving ProtonPlus host permission for the filesystem to see if the problem is directory permission.

**Comment by Arcitec** [comment]
@ChrisLauinger77 Thank you, I see the problem.

Your personal USER Steam data folder is a symlink to a directory owned by ROOT.

![image](https://github.com/user-attachments/assets/3dd9ad49-ec17-471e-9de6-833bf66ac683)

This causes two issues:

1. The ProtonPlus Flatpak does not have permission to access the host's `/opt/Steam/compatibilitytools.d` directory. It is simply not part of our filesystem access. So ProtonPlus inside the Flatpak sees a broken symlink at your `~/.local/share/Steam/compatibilitytools.d` that leads nowhere.
2. You need ROOT PERMISSIONS to write to `/opt`. It's a place where some native packages install their data. It is not a user-writable location.

Therefore this is not a bug in ProtonPlus and not something we have anything to do with.

The only question I have is why is your per-user compatibility tools a symlink to a root-location? It should never be that! Your per-user tools are per-user tools! It makes no sense at all to symlink that to a root location!

My theory would be that you manually created a root location to share all compatibility tools across all of your installed users.

That is not going to work with a tool like SteamTinkerLaunch, because that tool is not installed directly into `~/.local/share/Steam/compatibilitytools.d`. Instead, it's installed into `~/.local/share/steamtinkerlaunch`.

`~/.local/share/Steam/compatibilitytools.d/SteamTinkerLaunch/steamtinkerlaunch` will be a directory with a static symlink to exactly `/home/yourname/.local/share/steamtinkerlaunch/steamtinkerlaunch`.

This is not something we control. It's how SteamTinkerLaunch registers itself.

So, what can you do:

1. You can use Flatseal to give ProtonPlus access to `/opt/Steam/compatibilitytools.d` so that it has write-access for your downloads like GE-Proton.
2. Then you can continue sharing your compat tools across all users on the system.
3. But SteamTinkerLaunch will be broken in such a setup. So you cannot install SteamTinkerLaunch on your custom homebrew filesystem layout. Keep that in mind.

I hope this helps. :) This ticket may be useful for someone else who has modified their system layout in the future.

**Comment by ChrisLauinger77** [comment]
> @ChrisLauinger77 Thank you, I see the problem.
> 
> Your personal USER Steam data folder is a symlink to a directory owned by ROOT.
> 
> ![image](https://private-user-images.githubusercontent.com/38923130/367583846-3dd9ad49-ec17-471e-9de6-833bf66ac683.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY0MjAwMDUsIm5iZiI6MTcyNjQxOTcwNSwicGF0aCI6Ii8zODkyMzEzMC8zNjc1ODM4NDYtM2RkOWFkNDktZWMxNy00NzFlLTlkZTYtODMzYmY2NmFjNjgzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE1VDE3MDE0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRkZjAzYmU3NzU5ODQ5ZDg4ZDdjNjUzYjRmZTkwZGZmOWY0ZTNlOWU5NjQyMzVmMTgwN2U4MTc3NGU3NzFlZDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4V2_IsejebT3p-76qqdPAakWHiwOg8ul5hNPeUKLpuQ)
> 
> This causes two issues:
> 
>     1. The ProtonPlus Flatpak does not have permission to access the host's `/opt/Steam/compatibilitytools.d` directory. It is simply not part of our filesystem access. So ProtonPlus inside the Flatpak sees a broken symlink at your `~/.local/share/Steam/compatibilitytools.d` that leads nowhere. Therefore we cannot write/download anything to that location, since it "doesn't exist" for us!
> 
>     2. You need ROOT PERMISSIONS to write to `/opt`. It's a place where some native packages install their data. It is not a user-writable location.
> 
> 
> Therefore this is not a bug in ProtonPlus and not something we have anything to do with.
> 
> The only question I have is why is your per-user compatibility tools a symlink to a root-location? It should never be that! Your per-user tools are per-user tools! It makes no sense at all to symlink that to a root location!
> 
> My theory would be that you manually created a root location to share all compatibility tools across all of your installed users.
> 
> That is not going to work with a tool like SteamTinkerLaunch, because that tool is not installed directly into `~/.local/share/Steam/compatibilitytools.d`. Instead, it's installed into `~/.local/share/steamtinkerlaunch`.
> 
> `~/.local/share/Steam/compatibilitytools.d/SteamTinkerLaunch/steamtinkerlaunch` will be a directory with a static symlink to exactly `/home/yourname/.local/share/steamtinkerlaunch/steamtinkerlaunch`. Therefore, that link will only be valid per-user.
> 
> This is not something we control. It's how SteamTinkerLaunch registers itself.
> 
> So, what can you do:
> 
>     1. You can use Flatseal to give ProtonPlus access to `/opt/Steam/compatibilitytools.d` so that it has write-access for your downloads like GE-Proton.
> 
>     2. You need to use `sudo` to set permissions on `/opt/Steam/compatibilitytools.d` to make it writable by all your users on the system so that they can modify its contents.
> 
>     3. Then you can continue sharing your compat tools across all users on the system.
> 
>     4. But SteamTinkerLaunch will be broken in such a setup. So you **cannot install SteamTinkerLaunch** on your custom homebrew filesystem layout. Keep that in mind.
> 
> 
> I hope this helps. :) This ticket may be useful for someone else who has modified their system layout in the future.

it worked before the update - I doubt it is something on my side.
And secondly - the permissions are correct:
```
christian@debian:/opt/Steam$ dir
insgesamt 51628
drwxr-xr-x 39 christian users         4096 15. Sep 18:57 .
drwxr-xr-x  9 root      root          4096 30. Aug 17:35 ..
drwxr-xr-x  5 christian users         4096 15. Sep 18:57 appcache
drwxr-xr-x  2 christian users         4096 10. Feb 2023  Backups
lrwxrwxrwx  1 christian christian       28 15. Sep 08:58 bin -> /home/christian/.steam/bin32
lrwxrwxrwx  1 christian christian       22 15. Sep 08:58 bin32 -> /opt/Steam/ubuntu12_32
lrwxrwxrwx  1 christian christian       22 15. Sep 08:58 bin64 -> /opt/Steam/ubuntu12_64
-rwxr-xr-x  1 christian users        11384 10. Feb 2023  bin_steamdeps.py
-rw-r--r--  1 christian christian  3929144 15. Aug 19:38 bootstrap.tar.xz
drwxr-xr-x  2 christian users        20480 12. Sep 2023  cached
drwxr-xr-x  5 christian users         4096 17. Nov 2023  clientui
drwxr-xr-x  3 christian users         4096 14. Sep 17:29 compatibilitytools.d
```

**Comment by Vysp3r** [comment]
Did you try with the host filesystem permission?

**Comment by ChrisLauinger77** [comment]
> Did you try with the host filesystem permission?

Sorry, I missed this comment - yes with the host permission it works - thx

**Comment by Vysp3r** [comment]
Did you make manual modifications to have Steam in /opt?
I will not give our application an extra permission for that directory for a custom install.

**Comment by ChrisLauinger77** [comment]
Yes back in the day my home was on a nfs share. And steam on a local ssd.

**Comment by Vysp3r** [comment]
Alright well I will not add permission to /opt in the application itself, but you can keep it with the overridden permission for your use case

**Comment by Arcitec** [comment]
> it worked before the update - I doubt it is something on my side.

ProtonPlus has never had permission to `/opt`, so if it worked before the update then you have previously given it `host` or `/opt` permissions via Flatseal already.

The last version was in July, v0.4.13:

https://github.com/flathub/com.vysp3r.ProtonPlus/blob/4abc1c54dccc1584fffbf4bd5eea5f745243d190/com.vysp3r.ProtonPlus.json

You can see for yourself, we only had access to these directories:

```yml
        "--filesystem=~/.config/heroic",
        "--filesystem=~/.local/share/bottles"
        "--filesystem=~/.local/share/lutris",
        "--filesystem=~/.local/share/Steam",
        "--filesystem=~/.steam/root",
        "--filesystem=~/.var/app/com.heroicgameslauncher.hgl/config/heroic",
        "--filesystem=~/.var/app/com.usebottles.bottles/data/bottles",
        "--filesystem=~/.var/app/com.valvesoftware.Steam/data/Steam",
        "--filesystem=~/.var/app/net.lutris.Lutris/data/lutris",
        "--filesystem=xdg-run/gvfsd",
```

There is no `/opt` in there so no, it didn't "work before the update".

You have either used native ProtonPlus (non-Flatpak) before the update, which isn't sandboxed. Or you had manually given it permission for `/opt` which you've recently removed. ;) Those are the only options.

**Comment by ChrisLauinger77** [comment]
Maybe the flatpak update changed/modified the setting - I am sure it worked before the update - 100%

**Comment by ChrisLauinger77** [comment]
Only /opt/Steam - that sounds good. thx 4 the hint
