### ISSUE TITLE
Add Sarek

### ISSUE THREAD

**Issue by pythonlover02** [Vysp3r/ProtonPlus#248]
**Is your feature request related to a problem? Please describe.**
Nop

**Describe the solution you'd like**
Adding Proton-Sarek or Proton-For-Old-Vulkan Builds: https://github.com/pythonlover02/Proton-Sarek/tree/Stable

**Describe alternatives you've considered**
Manually downloading the Sarek builds

**Additional context**
Sarek (Proton-For-Old-Vulkan) is a custom Proton build featuring DXVK 1.10.3 and DXVK 1.10.3 Async, tailored for users with GPUs supporting Vulkan 1.1+ (but not 1.3+) and non-Vulkan setups. It offers patched versions of Proton-GE for improved performance on old hardware, with little enhancements to WineD3D. Originally created for two friends with GT 710 GPUs, the goal is to allow users with older GPUs to run Proton-GE without needing to use older versions.

Im the creator and main maintainer of the repo, i come here because some people would really like those builds to be on ProtonPlus for a more easy access, anything that i need to know, or do i am at the orders. :)

**Comment by Vysp3r** [comment]
I am going to be off for 2 months in a few days, but I will try my best to add it before I am going.

**Comment by Vysp3r** [comment]
I've added it, but the current way my application works makes it so I need to choose one element from the list of asset.
Could you tell me what do you plan the asset section to look like continuing forward otherwise if it's not stable I will not be able to add your runner to ProtonPlus.
![Screenshot from 2024-10-02 16-10-51](https://github.com/user-attachments/assets/113f4dec-1564-4200-be70-ce3e7c3279f8)
![Screenshot from 2024-10-02 16-12-07](https://github.com/user-attachments/assets/93410fe9-0751-4f02-a47d-950801f96b7d)

**Comment by pythonlover02** [comment]
> I've added it, but the current way my application works makes it so I need to choose one element from the list of asset. Could you tell me what do you plan the asset section to look like continuing forward otherwise if it's not stable I will not be able to add your runner to ProtonPlus. I am saying that because the first two don't have async, but have testing so if you plan on changing that a lot I would need to make something special just for your runner and I won't have time before I am going. ![Screenshot from 2024-10-02 16-10-51](https://private-user-images.githubusercontent.com/62019735/373019522-113f4dec-1564-4200-be70-ce3e7c3279f8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc5MDEzNjEsIm5iZiI6MTcyNzkwMTA2MSwicGF0aCI6Ii82MjAxOTczNS8zNzMwMTk1MjItMTEzZjRkZWMtMTU2NC00MjAwLWJlNzAtY2UzZTdjMzI3OWY4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDAyVDIwMzEwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgxOTE4MzEwZjU2NzdiZDU3Njg0ZWMwMGIwZGM4MTkyZDQzN2FmZDA2OWYyMDY4ZDM4MTQwMjg4MjdmOTZlODcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.veOuF2TzEueZs06-XITVkSW_J1VR5VGOm1vh-CHlMLc) ![Screenshot from 2024-10-02 16-12-07](https://private-user-images.githubusercontent.com/62019735/373019985-93410fe9-0751-4f02-a47d-950801f96b7d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc5MDEzNjEsIm5iZiI6MTcyNzkwMTA2MSwicGF0aCI6Ii82MjAxOTczNS8zNzMwMTk5ODUtOTM0MTBmZTktMDc1MS00ZjAyLWE0N2QtOTUwODAxZjk2YjdkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDAyVDIwMzEwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTViZjFiZmRiMTA1ZTRlYzFiYTI3MmZiMGZmMmMzZDdkOTBiNDIxZGViYTAyYTM2ZGUzNTIxZTBiMGI4NWU5ZjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.-q6lT98iozvOHhZlguRbk1xYm-pOSgxDtL_8-0hQZ-8)

Damn, that was really, really fast. As for what builds to display, show only the normal versions. The async versions could have issues with anticheat, so I don’t want them near someone who won’t read the documentation. The same goes for the testing builds, since being testing builds, they could even mess up some game prefixes.
This said, thanks for your work and for accepting mine in your program *:)*

**Comment by Vysp3r** [comment]
Okay so you don't want me to create a second entry for the async version?

Do you plan to keep the assets order like below or will that change?
![Screenshot from 2024-10-02 16-12-07](https://github.com/user-attachments/assets/70a546d6-2b57-44c7-bde8-7228f14ab7e6)

**Comment by pythonlover02** [comment]
> Okay so you don't want me to create a second entry for the async version?

If you can it would be awesome, but its not a priority.

> Do you plan to keep the assets order like below or will that change? ![Screenshot from 2024-10-02 16-12-07](https://private-user-images.githubusercontent.com/62019735/373030941-70a546d6-2b57-44c7-bde8-7228f14ab7e6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc5MDU0NjMsIm5iZiI6MTcyNzkwNTE2MywicGF0aCI6Ii82MjAxOTczNS8zNzMwMzA5NDEtNzBhNTQ2ZDYtMmI1Ny00NGM3LWJkZTgtNzIyOGYxNGFiN2U2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDAyVDIxMzkyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQwZmQ4ZDNmMDFmODliYjE1NGRkYzE1YzU4ZDBkYWJkZjZmMGYwZThlMmMxMDcxOGU0YTFhNGFmZmQ4OTU2ZDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.OoorcUqhKJTX92xXiCzE9xQErwSs1JJEtdDPs0QADl4)

About the assets it should always be like that unless i make a testing release. Also i will restructure the first release so all the releases always follow this order:  async - stable - testing or if you want an specific one that will make your life easy just say it and i will make it

**Comment by Vysp3r** [comment]
If the only thing that will not always be there is the testing releases, I am fine with whatever order you want as long as async and stable always exists and are in the same position.

**Comment by pythonlover02** [comment]
> If the only thing that will not always be there is the testing releases, I am fine with whatever order you want as long as async and stable always exists and are in the same position.

oh okey, async - stable - testing it is then.

**Comment by Vysp3r** [comment]
Okay, so I've excluded the 9.13 and 9.13-r1 since they weren't respecting that order and I will be creating a PR soon

**Comment by Vysp3r** [comment]
Just to make sure we're on the same page and for nothing to break on my end, just make sure you always have async and then stable in the assets in that order.

**Comment by pythonlover02** [comment]
> Just to make sure we're on the same page and for nothing to break on my end, just make sure you always have async and then stable in the assets in that order.

Yes i understand, also thanks for adding my build, its such an honor *:)*

**Comment by Vysp3r** [comment]
I made a release with it.
It should be available within 24h.

**Comment by Vysp3r** [comment]
I forgot to add your runner to the list of runner thats in the description of the application, but I'll make an hotfix tomorrow to fix that before I go.

**Comment by pythonlover02** [comment]
> I forgot to add your runner to the list of runner thats in the description of the application, but I'll make an hotfix tomorrow to fix that before I go.

No problem, sleep well :)

**Comment by Arcitec** [comment]
Normally, projects only had one asset, so we never had the issue before where we have to find the correct asset in a release.

But to make this more robust, we will be switching to regex to find assets instead of relying on the current positions.

You can subscribe to https://github.com/Vysp3r/ProtonPlus/issues/261 to keep track of when that issue is closed. Vysp3r will be gone for over a month and after that, regex will be added after the refactoring is complete, so I estimate around 2 months.

Until then, it's important that async is always the first asset and normal is always the second asset, as you confirmed already. :)

**Comment by pythonlover02** [comment]
> Normally, projects only had one asset, so we never had the issue before where we have to find the correct asset in a release.
> 
> But to make this more robust, we will be switching to regex to find assets instead of relying on the current positions.
> 
> You can subscribe to #261 to keep track of when that issue is closed. Vysp3r will be gone for over a month and after that, regex will be added after the refactoring #246 is complete, so I estimate around 2 months.
> 
> Until then, it's important that async is always the first asset and normal is always the second asset, as you confirmed already. :)

I’ll make sure that async is always the first asset and normal is the second. Also, i will keep an eye on #261 and #246 for updates. Thanks again for the clarity, and good luck with the refactor! :)
