### ISSUE TITLE
[BUG] Sarek Builds are inverted

### ISSUE THREAD

**Issue by pythonlover02** [Vysp3r/ProtonPlus#254]
**Describe the bug**
When downloading any Sarek Stable build, it actually downloads the Async version of that build. And when downloading an Async build, it downloads the Stable version instead. For example, when downloading the Sarek9-14-async build, it creates a folder called Sarek9-14_Async, but inside this folder, it actually extracts the normal Sarek9-14 instead of the Async version.

**Screenshots**
![image](https://github.com/user-attachments/assets/50e736b4-c176-4386-854b-0109d3b660fe)
![image](https://github.com/user-attachments/assets/ca04a1d2-a32a-40bb-8e8a-c90e92090c7f)

**Desktop (please complete the following information):**
 - OS: OpenSuse TW
 - DE: KDE 6
 - Type: ProtonPlus Flatpak

**Comment by Vysp3r** [comment]
Well I needed to push an hotfix anyway, I will fix that right away.

**Comment by Vysp3r** [comment]
I will create a new update in the coming hour

**Comment by Vysp3r** [comment]
The release was created.
It will be available on Flathub within 24h.

**Comment by pythonlover02** [comment]
> The release was created. It will be available on Flathub within 24h.
> 
> Sorry for the inconvenience :/

No problem, thanks for your hard work
