### ISSUE TITLE
[BUG] Stuck at extracting

### ISSUE THREAD

**Issue by windblows95** [Vysp3r/ProtonPlus#3]
**Describe the bug**

**To Reproduce**
1. Click on 'Add version'.
3. Select a compatibility tool and a version. 
4. Click on 'Install'.

**Expected behavior**
It should extract the newly downloaded version to the folder, but it is stuck on extracting.

**Screenshots**
![image](https://user-images.githubusercontent.com/64657372/192008531-45758bf5-f030-4504-8c35-ff58053b28e8.png)

**Desktop (please complete the following information):**
 - OS: Fedora 36 xm1 kernel
 - DE: GNOME 42.4
 - Type: Flatpak

**Additional info**
The newly downloaded and unsuccessfully decompressed version remains in the compatibility tool directory until I delete it.

**Comment by Vysp3r** [comment]
This issue was resolved in [this](https://github.com/Vysp3r/ProtonPlus/commit/d93ac5344d85b0bd13eeaed4ad7b69e505bc64c2) commit. Thanks you for your feedback!
