### ISSUE TITLE
[BUG] ProtonPlus does not remember the last launcher selected after a restart

### ISSUE THREAD

**Issue by Newbytee** [Vysp3r/ProtonPlus#34]
**Describe the bug**
Right now, on every restart of ProtonPlus, I have to change the launcher from Steam to Steam (Flatpak).

**To Reproduce**
1. Start ProtonPlus, and change the launcher
2. Restart ProtonPlus
3. Observe that the launcher has reverted to the default again rather than what you selected

**Expected behavior**
I would expect ProtonPlus to remember the last tool I had selected and default to that on startup. 

**Desktop (please complete the following information):**
 - OS: Fedora 37
 - DE: GNOME 43
 - Type: Flatpak from Flathub

**Comment by Vysp3r** [comment]
It would be more of a feature then a bug, but yes I agree that it would be a good idea. I'll work on that!

**Comment by Vysp3r** [comment]
I'm about 70% done on your request. I will include it in the next update!

**Comment by Vysp3r** [comment]
The feature is now in the dev branch! (https://github.com/Vysp3r/ProtonPlus/commit/79992d47631a02c71eb9bc5ff4bb955d4ff6f16a)
