### ISSUE TITLE
[BUG] Empty elements in the Kron4ek tool version combobox

### ISSUE THREAD

**Issue by windblows95** [Vysp3r/ProtonPlus#4]
**Describe the bug**
The version combobox has empty entries for the Kron4ek compatibility tool.

**To Reproduce**
1. Click on 'Add version'.
2. Select 'Kron4ek Wine-Builds Vanilla' tool.
3. Click on the version combobox.
4. See empty version entries.

**Expected behavior**
See only good entries.

**Screenshots**
![image](https://user-images.githubusercontent.com/64657372/192009724-1b7a1f35-eeb0-4d59-81fa-e9b3a6140123.png)

**Desktop (please complete the following information):**
 - OS: Fedora 36 xm1 kernel
 - DE: GNOME 42.4
 - Type: Flatpak

**Comment by Vysp3r** [comment]
This issue was resolved in [this](https://github.com/Vysp3r/ProtonPlus/commit/ab53ad3d301bd37f724b409322af7750ab284f9f) commit. Thanks you for your feedback!
