### ISSUE TITLE
[BUG] Pop up windows spamming and is not highlighted

### ISSUE THREAD

**Issue by wehagy** [Vysp3r/ProtonPlus#44]
**Describe the bug**
Every time I click on the "Launcher information", "Launcher settings" and "install a tool" buttons it creates a new pop up window, and it is not highlighted, and clicking on the 3-bar menu on any option is not highlighted.

**Expected behavior**
Lock user in popup window until it closes, gnome settings example if I click to add new network I can't click in the background window and the popup is highlighted (background window is dimmed).

https://user-images.githubusercontent.com/95216845/208213888-07751304-26fd-4f9b-a2c8-8ab9715365d3.mp4

**Screenshots**

https://user-images.githubusercontent.com/95216845/208213270-fc6a4da6-4b70-4e48-847f-3a087733daa2.mp4

https://user-images.githubusercontent.com/95216845/208213295-9f29f016-b377-4e61-8856-3cebc52893e0.mp4

**Desktop (please complete the following information):**
 - OS: Fedora 37
 - DE: GNOME 43
 - Type: Flatpak

**Additional context**
Builded using flatpak builder based on branch https://github.com/Vysp3r/ProtonPlus/tree/37-bugcritical-error-the-application-crashes-during-startup

**Comment by Vysp3r** [comment]
That's hella weird, the window opening function is not in a loop or anything that could do that. For the window being clickable while another one is open, I'll check what I can do.

**Comment by Vysp3r** [comment]
![image](https://user-images.githubusercontent.com/62019735/208304264-1334f35c-c2aa-4649-96d2-802c0b4e2742.png)

**Comment by Vysp3r** [comment]
Would you be able to test and tell me if it's now working properly? (Using the branch associated to this issue)

**Comment by wehagy** [comment]
Good work, tested and for some reason just the "About" option is not locked with main window, and I need to patch with branch [37-bugcritical-error-the-application-crashes-during-startup](https://github.com/Vysp3r/ProtonPlus/tree/37-bugcritical-error-the-application-crashes-during-startup).


https://user-images.githubusercontent.com/95216845/208335603-5c66f870-23c1-4463-b78b-899c07591094.mp4

**Comment by Vysp3r** [comment]
Oh, I didn't check if the About window support that, but I'll try! Sorry for you having to patch using that branch, I used main for those branch and not that branch.

**Comment by wehagy** [comment]
No problem :+1:, it's not too hard to me, and anyway the hard work is on you side.

**Comment by Vysp3r** [comment]
Okay, it should all be good now. If you approve of this I will add to the next update.

**Comment by wehagy** [comment]
"About" window is working now, everything is working fine now, nice job.

**Comment by Vysp3r** [comment]
Just to make sure you did not have the spamming thing happen with this version?

**Comment by Vysp3r** [comment]
Closing since it's now fixed. https://github.com/Vysp3r/ProtonPlus/commit/cdb6c2a6e2f6f42df4e7e500c609af914bcb9619
