### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by IPlayZed** [Vysp3r/ProtonPlus#47]
**Describe the bug**
ProtonPlus fails to launch.

**To Reproduce**
1. Install the Flatpak version as user.
2. Try to launch it from either the terminal or from a desktop entry.

**Expected behavior**
ProtonPlus should launch.

**Screenshots**
![image](https://user-images.githubusercontent.com/21132316/208657623-cea16846-366c-4010-b39b-5e1ae12d9854.png)

**Desktop (please complete the following information):**
 - OS: Arch Linux x86_64 (6.0.12-arch1-1)
 - DE: GNOME 43.2
 - Type: Flatpak (0.3.1) (installed as user application

**Additional context**
I did theming with Gradience, and rolled it back, however it didn't change anything.

**Comment by Vysp3r** [comment]
Closing since duplicate. See https://github.com/Vysp3r/ProtonPlus/issues/37
