### ISSUE TITLE
[BUG] :children_crossing: No option to cancel the download of a compatibility tool

### ISSUE THREAD

**Issue by wehagy** [Vysp3r/ProtonPlus#48]
**Describe the bug**
No option to cancel the download of a compatibility tool.

**To Reproduce**
1. Click to "Install a tool".
2. Select the tool to install.
3. Click on "Install".
4. I don't want the tool anymore, but the download don't have finished yet.
5. I have no option to cancel the download, and if I close the "Install a tool" window what happens?

**Expected behavior**
Option to cancel the download if I don't want. See below print from ProtonUp-Qt.

![Screenshot from 2022-12-20 23-36-47](https://user-images.githubusercontent.com/95216845/208807911-34e71544-5e62-4dfe-8f35-d372d0f8775a.png)

**Desktop (please complete the following information):**
 - OS: Debian Bookworm/Testing
 - DE: GNOME 43
 - Type: Flatpak

**Additional context**
Using [dev](https://github.com/Vysp3r/ProtonPlus/tree/dev) branch.

Tested what happens if I close the "install a tool" window, if I don't close the app the installation finish anyway.

**Comment by Vysp3r** [comment]
Yeah, it was already in my todo list ahah. Shouldn't be too long to add.

**Comment by wehagy** [comment]
Nice, I think you can use that issue to track this :sweat_smile:

**Comment by Vysp3r** [comment]
The new download method was tested and is working properly. I will implement that in the next update with a way to cancel the download at the same time.

**Comment by wehagy** [comment]
I think it's going to be a small but good fix.

**Comment by Vysp3r** [comment]
I was able to make that when you exit the window, it deletes the files so that nothing is left behind. I will not add a pop up asking to make sure you want to exit for now since it would require a rewrite of something and I wish to get the next update out before doing that.

**Comment by Vysp3r** [comment]
I still miss the pop up to add like I said earlier, but the files should no longer appear if you close the window during an installation. Here's the commit in case you're interested https://github.com/Vysp3r/ProtonPlus/commit/7fd6d15aba8343ba0a61ebf9ee3b37c876540bc2.

**Comment by wehagy** [comment]
I dunno if this is expected for now, but if I'm downloading and close the window, the message `Cancelled!` appears, and I can't download without closing and opening the app, the files is removed. If I click to close the window on extraction, the same happens, but not all the files is removed, but I think it's because of the #43 and unrelated.

**Comment by Vysp3r** [comment]
Yeah, it's probably due to that issue indeed. I'll test on my end a bit more to make sure there's really no problem with that tho.

**Comment by Vysp3r** [comment]
I will work on this this week.

**Comment by Vysp3r** [comment]
My friend fixed it in https://github.com/Vysp3r/ProtonPlus/pull/84. It will be available in the next update. I will now close this issue.
