### ISSUE TITLE
[FEATURE] :memo: Add instructions how to build from source with flatpak

### ISSUE THREAD

**Issue by wehagy** [Vysp3r/ProtonPlus#49]
**Describe the solution you'd like**
Flatpak is the official way to distribute the app, it makes sense that the project has instructions on how to build from source using flatpak for anyone who wants to contribute.

**Additional context**
Can assign me, I am working on this.

### Checklist:

- [x] Check the distro package manager dependencies.
- [x] Check the flatpak package manager dependencies.
- [x] Make necessary adjustments to upstream code.
- [x] Make some tests to see if everything is working as intended.
- [x] Update README.md.

**Comment by Vysp3r** [comment]
There you go, have fun :)

**Comment by wehagy** [comment]
If i don't want to break my keyboard, it's fine :laughing:

**Comment by wehagy** [comment]
I've made a draft pull request of what I think the README.md should look like, if you can see what you think it looks like, but I'll probably tweak it a bit.

**Comment by Vysp3r** [comment]
Just reviewed it :)
