### ISSUE TITLE
[BUG] Clicking on "Install a tool" causes ProtonPlus to hang indefinitely

### ISSUE THREAD

**Issue by LinuxJoeUser** [Vysp3r/ProtonPlus#52]
**Describe the bug**
Clicking on "Install a tool" causes (flatpak) ProtonPlus to hang indefinitely

**To Reproduce**
1. Launch gui or cli ProtonPlus v0.3.1
2. Click on 'Install a tool'

Operating System: Kubuntu 22.10
KDE Plasma Version: 5.25.5
KDE Frameworks Version: 5.98.0
Qt Version: 5.15.6
Kernel Version: 5.19.0-26-generic (64-bit)
Graphics Platform: X11
Processors: 24 × AMD Ryzen 9 3900X 12-Core Processor
Memory: 31.3 GiB of RAM
Graphics Processor: NVIDIA GeForce GTX 1070/PCIe/SSE2
Manufacturer: Gigabyte Technology Co., Ltd.
Product Name: X570 AORUS ELITE
System Version: -CF

Here's what I see from running ProtonPlus from cli:
```
~$ flatpak run -v com.vysp3r.ProtonPlus
F: No installations directory in /etc/flatpak/installations.d. Skipping
F: Opening system flatpak installation at path /var/lib/flatpak
F: Opening user flatpak installation at path /home/gw/.local/share/flatpak
F: Opening user flatpak installation at path /home/gw/.local/share/flatpak
F: Opening system flatpak installation at path /var/lib/flatpak
F: Skipping parental controls check for app/com.vysp3r.ProtonPlus/x86_64/stable since parental controls are disabled globally
F: Opening user flatpak installation at path /home/gw/.local/share/flatpak
F: Opening system flatpak installation at path /var/lib/flatpak
F: /var/lib/flatpak/runtime/org.gnome.Platform/x86_64/43/c01cb33cf898efab6b025c9a64480c6dc201ced293de7f49cd126a93659d3d3f/files/lib32 does not exist
F: Cleaning up unused container id 3849027056
F: Cleaning up per-app-ID state for com.vysp3r.ProtonPlus
F: Allocated instance id 922735527
F: Add defaults in dir /com/vysp3r/ProtonPlus/
F: Add locks in dir /com/vysp3r/ProtonPlus/
F: Allowing dri access
F: Allowing wayland access
F: Allowing x11 access
F: Running 'bwrap --args 40 xdg-dbus-proxy --args=42'
F: Running 'bwrap --args 40 protonplus'
The specified location is not supported
~$
```

Let me know what else I can do for you to help you troubleshoot.

**Comment by Vysp3r** [comment]
I never used flatpak run with -v, I guess it's for verbose and the stuff that starts with F: is only shown when you add -v. In that case that would mean that when you click 'Install a tool' the message 'The specified location is not supported' appears. Am I right?

**Comment by Vysp3r** [comment]
Once you're free, I will need more information so that I can fix your problem.

**Comment by Vysp3r** [comment]
If I don't hear anything by the end of the week, I will close this issue until you become active.

**Comment by Vysp3r** [comment]
Closing since inactive.
