### ISSUE TITLE
[BUG] Compatibility tool Luxtorpeda not always with the correct name in the UI

### ISSUE THREAD

**Issue by wehagy** [Vysp3r/ProtonPlus#53]
**Describe the bug**
Downloading the compatibility tool Luxtorpeda not always update the UI from the app.

**To Reproduce**
1. Click to install a tool.
2. Select Luxtorpeda as a download compatibility tool.
3. Click to install Luxtorpeda and see what happens below (Pay attention to the name of Luxtorpeda in the list of installed compatibility tools)

**Expected behavior**
The correct Luxtorpeda name and version in the list of installed compatibility tools.

**Screenshots**

https://user-images.githubusercontent.com/95216845/209290796-234cd351-c185-42f6-8549-f44384b288e1.mp4

**Desktop (please complete the following information):**
 - OS: Debian Boowork/Testing
 - DE: GNOME 43
 - Type: Flatpak

**Additional context**
Tested on [dev](https://github.com/Vysp3r/ProtonPlus/tree/dev) branch and my patched branch with [37-bugcritical-error-the-application-crashes-during-startup](https://github.com/Vysp3r/ProtonPlus/tree/37-bugcritical-error-the-application-crashes-during-startup) and [43-bug-dont-auto-prune-targz-files-and-dont-remove-the-compatibility-tools-from-the-ui](https://github.com/Vysp3r/ProtonPlus/tree/43-bug-dont-auto-prune-targz-files-and-dont-remove-the-compatibility-tools-from-the-ui) branches.

**Comment by Vysp3r** [comment]
The tool got the correct name, the thing is I rename the directory `luxtorpeda` and refresh the list, but sometimes the refresh happens too fast so `luxtorpeda` is showed instead of the new name. I'll try ti find a way to find a way to always refresh the list after the rename.

**Comment by Vysp3r** [comment]
Oh damn, I was moving the file to rename them.  That was the problem ahah. I instead used the rename function. It should work now using the 'dev' branch.

**Comment by wehagy** [comment]
Strange, now the first one downloaded works, the second the name `luxtorpeda` appers and from the third onwards it works as it should.


https://user-images.githubusercontent.com/95216845/209418677-06b18266-8843-4ced-a772-001c068538c0.mp4

**Comment by Vysp3r** [comment]
Does that work any better for you?
https://github.com/Vysp3r/ProtonPlus/commit/69c89a1ea0261b468b28f631ccb3d42574f4825c

**Comment by wehagy** [comment]
Fixed, the `Luxtorpeda` name is updating.
