### ISSUE TITLE
[BUG] Tools are not downloaded.

### ISSUE THREAD

**Issue by smotim** [Vysp3r/ProtonPlus#54]
**Describe the bug**
In versions after 0.2.3 (installed from flathub), after selecting the version of the tool, a loading bar appears, but does not move anywhere for a long time. The folder for the downloaded version is also not created. If you run it through Builder, in the "application output" section, after clicking on "download", the inscription "action is not supported" appears

**To Reproduce**
1. Choose any version of the tool for any launcher
2. Click install
3. See error

**Desktop (please complete the following information):**
 - OS: fedora 37
 - DE: gnome 43.2
 - Type: source and Flatpak

**Additional context**
This error was also discussed here #37  (near the end of the issue)

**Comment by Vysp3r** [comment]
I asked ChatGPT to help me find a new to download files in Vala and he showed me a few examples. I should be able to get something working for you soon.

**Comment by Vysp3r** [comment]
You can test the branch from this issue. I've rebased it on the 'dev' branch so that you don't have to yourself. I did not make the progress bar work for now, but if I know that this way the download is working, I'll spend more time on it to make it exactly like before.

**Comment by smotim** [comment]
Made a checkout on the dev branch. Nothing seems to have changed. The same "action is not supported" message appears

**Comment by smotim** [comment]
Yes, this way works. The tool was downloaded and installed.

**Comment by Vysp3r** [comment]
What a great news to hear. I'll implement that in the next update!

**Comment by Vysp3r** [comment]
This fix was added in https://github.com/Vysp3r/ProtonPlus/commit/7fd6d15aba8343ba0a61ebf9ee3b37c876540bc2. I will now close this issue. If the problem still happen, reopen this issue.
