### ISSUE TITLE
[BUG] Can't open the app with the app grid, just by GNOME Software

### ISSUE THREAD

**Issue by MDuardo-CO** [Vysp3r/ProtonPlus#61]
ProtonPlus fails to launch with the app grid but the app opens through GNOME Software.

https://user-images.githubusercontent.com/62776855/210639258-fe3d9b1a-7ad3-4f01-8859-a99a9d48df19.mp4

1. Go to the app grid
2. Click on ProtonPlus
3. See the error

Desktop
 - OS: Ultramarine Linux 36
 - DE: GNOME 42.4
 - Display server: Wayland
 - Type: Flatpak from Flathub

Disabling all extensions doesn't fix the problem and all other apps work flawlessly.

**Comment by Vysp3r** [comment]
Damn, I forgot to update the desktop file!
My bad, I'll fix that right away.

**Comment by Vysp3r** [comment]
Fixed in https://github.com/Vysp3r/ProtonPlus/commit/0a3151196ae5233ae8a7c20e90b4278000b236d5!

**Comment by MDuardo-CO** [comment]
Thanks man, I appreciate it.
