### ISSUE TITLE
[FEATURE] Install Proton for Steam flatpak in a way that enables using it with gamescope flatpak

### ISSUE THREAD

**Issue by mystrdat** [Vysp3r/ProtonPlus#63]
**Is your feature request related to a problem? Please describe.**
If you're using Steam flatpak + [gamescope flatpak](https://github.com/flathub/com.valvesoftware.Steam.Utility.gamescope), you can currently only use the [community releases](https://github.com/flathub/com.valvesoftware.Steam.CompatibilityTool.Proton-GE) of Proton/ProtonGE otherwise gamescope just doesn't work. See issue https://github.com/flathub/com.valvesoftware.Steam.Utility.gamescope/issues/7 for details. Would you be able to bypass this issue when installing Proton into Steam flatpak with ProtonPlus, perhaps as an installation option?

Here's a quote from the above issue describing the origin of the problem
> The unofficial Proton versions provided in Flathub do not package or use pressure-vessel. In this case there's no subsandbox involved and games have access to gamescope's X11 socket because they run in the same sandbox. This is why using unofficial Proton versions "works around" the issue.

**Describe the solution you'd like**
I would like to use ProtonPlus installed tools with flatpak gamescope.

**Describe alternatives you've considered**
An alternative would be not using Steam/gamescope flatpak or waiting until the issue is fixed, which is looking like a long term problem.

**Additional context**
https://github.com/flathub/com.valvesoftware.Steam.Utility.gamescope/issues/7

**Comment by Vysp3r** [comment]
1. So basically it works right now if you're not using Gamescope?
2. Will I need to make ProtonPlus install the flatpak of ProtonGE or I can download  a zip and extract it like every other launcher?

**Comment by mystrdat** [comment]
I must say I do have somewhat limited understanding of the whole picture - from reading various issues it looks like this is something that needs to be eventually fixed between all of Flatpak, Steam and Gamescope and it's moving in that direction, but it seems pretty involved and who knows how long it will take. At the same time, it's probably quite unknown to the average Steam user.

If you install Steam from Flathub through Gnome Software or else with gamescope which is listed there as an addon (which seems to be becoming the mainstream path to installing Steam), gamescope just won't work by default. I made the issue here because this is one of the two apps (with ProtonUpQT) that are becoming quite widespread for managing Proton among these communities and you are possibly in a unique position to maybe bypass this problem for the time being, so the average user that just wants to copy some ProtonDB launch options with gamescope in it has things working.

1. Yes, the issue is only related to the flatpak version of gamescope - currenly no other version of Proton other than the [community flatpak releases](https://github.com/flathub/com.valvesoftware.Steam.CompatibilityTool.Proton-GE) works with it, not even the Steam-bundled official versions. As I understand it, these versions work because they patch out `pressure-vessel` (some kind of valve flatpak-like containerization/sandbox).

2. I'm not 100% sure, but you probably don't need to install it as flatpak - just needs to be copied to the right folders. It will lose the option of being updated through flatpak but that's the purpose of your tool anyway. Also perhaps there should be some kind of a notice or explanation that these versions are needed only if you want to use flatpak gamescope.

**Comment by Vysp3r** [comment]
Alright, I'll try to come up with something for that in the next update. I will work on that this weekend. 
If I can simply download them it will be really easy otherwise I'm not sure how I could do it if not installing the flatpak.

**Comment by Vysp3r** [comment]
@mystrdat would you be able to download and install this manually https://github.com/Lctrs/proton-ge-custom-tarball-maker/releases/download/GE-Proton7-43-1/proton-ge-custom-src.tar.xz in /home/vysp3r/.var/app/com.valvesoftware.Steam/.steam/steam/compatibilitytools.d and tell me if that works for you using gamescope?

**Comment by Lctrs** [comment]
This won't work. We're just building an archive of the sources, and not the binaries, of Proton GE in this repository to reduce build time on flatpak side.

**Comment by Vysp3r** [comment]
Since @Lctrs told me I would probably need to mimick what they do when you install the community version, the only way I could see myself implement that in my app would be to add a warning (that you can disable after viewing it one time) when you try to add a tool for Steam (Flatpak). What do you think @mystrdat?

**Comment by mystrdat** [comment]
Hey @Vysp3r, apologies I wasn't at my gaming machine to try during the weekend. Looks like too much effort to recreate these builds on your end. I think making people installing Proton with ProtonPlus aware of this existing limitation between flatpak gamescope and Proton is the next best thing, and hopefully it will be resolved in the near future between all these libraries properly. Thanks for looking into it!

**Comment by Vysp3r** [comment]
Added in https://github.com/Vysp3r/ProtonPlus/commit/aa4885f39ba532ef6db7558a98f58fd943c4ad2c.
