### ISSUE TITLE
[FEATURE] Add TKG proton builds

### ISSUE THREAD

**Issue by massatt212** [Vysp3r/ProtonPlus#69]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

https://github.com/Frogging-Family/wine-tkg-git
https://github.com/Frogging-Family/wine-tkg-git/actions/workflows/proton-valvexbe-arch-nopackage.yml

**Comment by Vysp3r** [comment]
I will check on how complex it is to add since they're not using Releases but Actions. If it's not too complex, I will try to add it this weekend.

**Comment by Vysp3r** [comment]
Just for you to know, I'm working on that right now. I hope for it to be ready in a few hours max. Probably less, but we never know.

**Comment by Vysp3r** [comment]
I was able to add it and have the releases show up correctly, but the download is not working with my current download method. I will push what I have so far, but I don't know if I will finish that today, because of that.

**Comment by Vysp3r** [comment]
Got it working, I will make an update soon.

**Comment by Vysp3r** [comment]
Added in https://github.com/Vysp3r/ProtonPlus/commit/934362ad519c7fba9f3fd2e4d03ab934e62c7f39.

**Comment by massatt212** [comment]
TKG removed in latest update?

**Comment by Vysp3r** [comment]
Yep, it wasn't even working in the update before. I wanted to push this update and since Proton Tkg is special and requires a little more work then the others well I decided to remove it until the next update. Don't worry it will come back.

**Comment by massatt212** [comment]
It was working before, I used everyday

**Comment by Vysp3r** [comment]
I tested the last few versions and it never worked. I don't know what to tell you.

**Comment by massatt212** [comment]
Strange, it always worked for me 😂

**Comment by Vysp3r** [comment]
True. Thing is I didn't want to leave something that was not properly working in. I'll try to re-add it this weekend.

**Comment by Vysp3r** [comment]
I will try to fix this tonight and push an update as soon as I can. Sorry for the delay.

**Comment by Vysp3r** [comment]
Fixed in https://github.com/Vysp3r/ProtonPlus/pull/121.

**Comment by massatt212** [comment]
alright

**Comment by Vysp3r** [comment]
It should be available in the latest update.
