### ISSUE TITLE
[BUG] DXVK update is missing

### ISSUE THREAD

**Issue by hyknn** [Vysp3r/ProtonPlus#85]
**Describe the bug**
If I'm not wrong u have included a feature where we can update dxvk version on the previous version. Is it removed?

**To Reproduce**
1. Go to 'ProtonPlus'
2. Click on 'Launcher'
3. Scroll down to 'DXVK'

**Expected behavior**
There is DXVK option for updating DXVK

**Screenshots**
![image](https://user-images.githubusercontent.com/60916302/222410114-bad9ba03-034e-4384-b92c-56867d2d3c67.png)

**Desktop (please complete the following information):**
 - OS: Pop!_OS 22.04 LTS
 - DE: GNOME 42.5
 - Type: Flatpak

**Comment by hyknn** [comment]
No, I didn't touch anything. I've also checked that the dxvk folder exists

![image](https://user-images.githubusercontent.com/60916302/222433013-437daebb-76d8-49d0-abf7-1908ab68fda7.png)

**Comment by Vysp3r** [comment]
I will look into that today. Did you touch anything in the lutris folder by any chance? Because on a fresh install luttis creates the dxvk folder sonit shojld appear.
